INSERT INTO bears (name, age, gender color, color, temperament, alive) VALUES ("Mr. Chocolate", 7, "M", )
INSERT INTO bears (name, age, gender color, color, temperament, alive) VALUES ()
INSERT INTO bears (name, age, gender color, color, temperament, alive) VALUES ()
INSERT INTO bears (name, age, gender color, color, temperament, alive) VALUES ()
INSERT INTO bears (name, age, gender color, color, temperament, alive) VALUES ()
INSERT INTO bears (name, age, gender color, color, temperament, alive) VALUES ()
INSERT INTO bears (name, age, gender color, color, temperament, alive) VALUES ()
INSERT INTO bears (name, age, gender color, color, temperament, alive) VALUES ()